### ISSUE TITLE
Prepare Frisbee for RPC Framework

### ISSUE THREAD

**Issue by ShivanshVij** [loopholelabs/frisbee#59]
We need certain functions inside Frisbee that will allow us to implement the RPC framework. Moreover, we need better memory management and no longer require streams (streams are also something we do not want to support). 

In order for us to build an RPC framework on top of Frisbee (https://lucid.app/lucidchart/b3c5f138-eea7-41c2-a8ab-4919c188f0a1/edit?beaconFlowId=B0F62EEBA36C1A95&invitationId=inv_2665fc0e-5194-4a6a-96e9-dcbe4ab6b9b5&page=0_0#) we need to support asynchronous handlers, which is the main focus of this issue. 

Acceptance Criteria:
- [ ] Frisbee No Longer supports streams
- [ ] Frisbee no longer uses frisbee.Message and instead uses *packet.Packet to re-use memory and avoid allocations
- [ ] Frisbee messages have lower overhead (and no longer contain the `to` and `from` field which we never used anyways)

**Comment by Jspsun** [comment]
Lucid chart is private. Requested access!

**Comment by ShivanshVij** [comment]
> Lucid chart is private. Requested access!

My bad, fixed: https://lucid.app/lucidchart/invitations/accept/inv_3ca2a7e6-a8f5-423f-ae64-8dfc11a4a1cf
